# Generated by Django 3.0.5 on 2020-04-22 15:54

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.models.content_file_name)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('verification', models.CharField(choices=[('UV', 'Unverified'), ('F', 'Fake'), ('V', 'Verified')], default='UV', max_length=2)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
